name: japanese_words_app
description: A Japanese word learning app with spaced repetition
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  path: ^1.8.3
  path_provider: ^2.1.1
  intl: ^0.18.1
  google_fonts: ^6.1.0
  share_plus: ^7.2.1
  file_picker: ^8.1.3
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256


flutter:
  uses-material-design: true

  assets:
    - assets/icon.png

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700
